version: '3'
services:
  app:
    build: .
    command: bash
    environment:
      - DATABASE_PASSWORD=root
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
